### ISSUE TITLE
No module named 'pysc2.lib.typeenums'

### ISSUE THREAD

**Issue by QianSL** [tencent-ailab/TLeague#14]
The error come out while running 

> "bash example_sc2_sp_ppo2.sh learner"
mentioned in 
> "docs/EXAMPLE_SC2_SP_PPO2.md"

The traceback info are:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/tleague/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/miniconda3/envs/tleague/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/xx/Documents/code/TLeague/tleague/bin/run_pg_learner.py", line 138, in <module>
    app.run(main)
  File "/opt/miniconda3/envs/tleague/lib/python3.6/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/opt/miniconda3/envs/tleague/lib/python3.6/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/Users/xx/Documents/code/TLeague/tleague/bin/run_pg_learner.py", line 93, in main
    ob_space, ac_space = env_space(FLAGS.env, env_config, interface_config)
  File "/Users/xx/Documents/code/TLeague/tleague/envs/create_envs.py", line 74, in env_space
    from tleague.envs.sc2 import sc2_env_space
  File "/Users/xx/Documents/code/TLeague/tleague/envs/sc2/__init__.py", line 1, in <module>
    from .create_sc2_envs import *
  File "/Users/xx/Documents/code/TLeague/tleague/envs/sc2/create_sc2_envs.py", line 11, in <module>
    from arena.wrappers.sc2_wrapper import VecRwd
  File "/Users/xx/Documents/code/Arena/arena/wrappers/sc2_wrapper.py", line 2, in <module>
    from arena.utils.constant import AllianceType
  File "/Users/xx/Documents/code/Arena/arena/utils/constant.py", line 2, in <module>
    from pysc2.lib.typeenums import UNIT_TYPEID
ModuleNotFoundError: No module named 'pysc2.lib.typeenums'

related libs are:
TImitate             1.3                 /Users/xx/Documents/code/TImitate
TLeague              1.3                 /Users/xx/Documents/code/TLeague
TPolicies            1.3                 /Users/xx/Documents/code/TPolicies

python: 3.6.13
MacOS

If you need any more info, please let me know.
And I tried different version of pysc2 from v1.0 to v3.0, there is always this error.

Thank you~

**Comment by pengsun** [comment]
Hi, you need install a specific pysc2 fork, as is described in the following links:
https://github.com/tencent-ailab/tleague_projpage#starcraft-ii-training
https://github.com/tencent-ailab/TImitate#install

which should work ~

**Comment by QianSL** [comment]
Thank you!
