### ISSUE TITLE
AssertionError with PBTPSROGameMgr

### ISSUE THREAD

**Issue by ismeyueyue** [tencent-ailab/TLeague#17]
set `game_mgr_type=tleague.game_mgr.game_mgrs.PBTPSROGameMgr`

During the 'request_learner_task' process, 
https://github.com/tencent-ailab/TLeague/blob/cc5e13abd2b1610720f042805e5cdffc660e2c3c/tleague/league_mgrs/league_mgr.py#L125
a new model_key is got using the game_mgr based on cur_model_key, however, the diversity of the current player is less than the threshold, game_mgr sets `self._population[current_player].is_living = False` to kill the current player and randomly selects another player. 
https://github.com/tencent-ailab/TLeague/blob/cc5e13abd2b1610720f042805e5cdffc660e2c3c/tleague/game_mgr/game_mgrs.py#L402
After several debugs, I found that the population size was always one, as the new model key is either None or equal to the  cur_model_key and cannot be added to the population. As a result, an error occurred when selecting another player. 
https://github.com/tencent-ailab/TLeague/blob/cc5e13abd2b1610720f042805e5cdffc660e2c3c/tleague/game_mgr/game_mgrs.py#L404
Blow is my debug log:
```
_on_request_learner_task:  done adding player rand_model:0001, parent_player rand_model:0001, to game mgr
_on_request_learner_task: learner_id:'lrngrp0'
Traceback (most recent call last):
  File "/Users/huyueyue/opt/anaconda3/envs/rl/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/huyueyue/opt/anaconda3/envs/rl/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/huyueyue/Work/Code/TLeague/tleague/bin/run_league_mgr.py", line 107, in <module>
    app.run(main)
  File "/Users/huyueyue/opt/anaconda3/envs/rl/lib/python3.6/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/Users/huyueyue/opt/anaconda3/envs/rl/lib/python3.6/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/Users/huyueyue/Work/Code/TLeague/tleague/bin/run_league_mgr.py", line 103, in main
    league_mgr.run()
  File "/Users/huyueyue/Work/Code/TLeague/tleague/league_mgrs/base_league_mgr.py", line 72, in run
    learner_task = self._on_request_learner_task(learner_id)
  File "/Users/huyueyue/Work/Code/TLeague/tleague/league_mgrs/league_mgr.py", line 125, in _on_request_learner_task
    parent_model_key, is_mutate = self.game_mgr.get_player(cur_model_key)
  File "/Users/huyueyue/Work/Code/TLeague/tleague/game_mgr/game_mgrs.py", line 404, in get_player
    assert len(living_players) > 0
AssertionError
```

There seems to be a problem with the code, please help check it.
Thks.

**Comment by ismeyueyue** [comment]
Did I got it wrong……？
